# Files in the project. Make sure the first file is the top module
VHD = vga_lab.vhd vga_motor.vhd char_rom.vhd ../video_ram.vhd

# Design constraints file
XDC = Basys3.xdc

# Testbench file
TBF = vga_lab_tb.vhd

# Include Makefile utilities
include /courses/TSEA83/bin/util.mk
