# Files in the project. Make sure the first file is the top module
VHD = vga_lab.vhd kbd_enc.vhd pret_cpu.vhd video_ram.vhd vga_motor/vga_motor.vhd vga_motor/char_rom.vhd

# Design constraints file
XDC = Basys3.xdc

# Testbench file
TBF = vga_lab_tb.vhd

# Include Makefile utilities
include /courses/TSEA83/bin/util.mk
